# 100_load_datasets

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [27]:
sexWork_df = pd.read_csv('../../data/raw/online_sex_work.csv')
sexWork_df

C:\Users\bolu_\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,User_ID,Gender,Age,Location,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Points_Rank,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_advertisments_posted,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
0,10386.0,male,"34,6",A,Non_Verified,Homosexual,Switch,Men,50,before_10_days,17.9.2012,32,0:2,0.0,0.0,0.0,18260,No_risk
1,14.0,male,"32,2",J,Non_Verified,Heterosexual,Dominant,Women,518,before_1_days,1.11.2009,710,3:45,9.0,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk
2,16721.0,male,"33,6",K,Non_Verified,Heterosexual,Dominant,Women,150,before_3_days,1.4.2013,25,2:15,1.0,1.0,45.0,"19805,21721,19802",No_risk
3,16957.0,male,34,H,Non_Verified,Heterosexual,Dominant,Women,114,before_4_days,8.4.2013,107,359:22,1.0,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk
4,17125.0,male,"39,5",B,Non_Verified,Heterosexual,Dominant,Women,497,before_5_days,14.4.2013,600,0:21,0.0,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk
5,17220.0,female,"47,8",A,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,127,before_1_days,19.4.2013,159,1 436:52,1.0,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk
6,1726.0,male,"36,7",B,Non_Verified,bicurious,Submisive,Women,18,before_1_days,16.10.2010,1,122:20,17.0,0.0,0.0,NaN,No_risk
7,1750.0,male,51,L,Non_Verified,Heterosexual,Dominant,Nobody,38,before_9_days,22.10.2010,91,0:5,0.0,0.0,2.0,28050,No_risk
8,18162.0,female,"29,5",A,Non_Verified,bicurious,Submisive,Nobody_but_maybe,150,before_4_days,23.5.2013,278,84:19,0.0,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk
9,18820.0,male,28,J,Non_Verified,Heterosexual,Switch,Women,-26,before_1_days,12.6.2013,4,3:23,0.0,0.0,0.0,"40351,24148,43311",No_risk
10,19437.0,male,"42,9",A,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,15,before_1_days,7.7.2013,0,2:2,0.0,0.0,0.0,"32531,38201,24377,42617",No_risk
11,19732.0,female,"45,4",A,Non_Verified,Heterosexual,Submisive,Nobody,36,before_3_days,17.7.2013,47,331:18,0.0,11.0,0.0,"24922,47795,22079,24055,20197,22397,43342,3237...",No_risk
12,19781.0,male,"36,1",F,Non_Verified,Heterosexual,Switch,Women,30,before_1_days,19.7.2013,0,139:53,0.0,0.0,0.0,"27687,30821",No_risk
13,19805.0,male,42,H,Verified,Heterosexual,Dominant,Nobody_but_maybe,313,before_1_days,20.7.2013,51,508:8,0.0,5.0,0.0,"29362,33755,22397,19878,16604,20811,2524,19732...",No_risk
14,19990.0,male,"36,8",E,Non_Verified,Heterosexual,Submisive,Women,0,before_62_days,28.7.2013,0,45:24,0.0,0.0,0.0,NaN,No_risk
15,20926.0,male,"30,9",A,Non_Verified,Heterosexual,Submisive,Nobody_but_maybe,15,before_1_days,2.9.2013,0,10:41,0.0,0.0,0.0,NaN,No_risk
16,21471.0,male,"33,9",B,Verified,Heterosexual,Dominant,Women,155,before_3_days,26.9.2013,59,0:0,1.0,0.0,0.0,32494,No_risk
17,22458.0,female,"48,6",L,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,236,before_1_days,5.11.2013,501,0:0,0.0,0.0,25.0,NaN,No_risk
18,24160.0,male,"56,2",K,Non_Verified,Heterosexual,Submisive,Women,60,before_315_days,10.1.2014,68,115:34,2.0,0.0,0.0,"24707,2336",No_risk
19,25379.0,male,"35,3",A,Non_Verified,Heterosexual,Submisive,Women,18,before_6_days,4.3.2014,3,3:25,1.0,0.0,0.0,NaN,No_risk
20,27804.0,female,"23,8",B,Non_Verified,bisexual,Submisive,Nobody,29,before_3_days,24.6.2014,247,1:25,0.0,0.0,5.0,8696,No_risk
21,27813.0,male,"35,3",A,Non_Verified,Heterosexual,Submisive,Nobody,0,before_15_days,24.6.2014,0,3:20,0.0,0.0,0.0,NaN,No_risk
22,3030.0,male,"36,7",A,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,564,before_1_days,14.6.2011,845,0:4,0.0,0.0,0.0,32032,No_risk
23,31596.0,male,"39,3",K,Verified,Heterosexual,Dominant,Nobody_but_maybe,296,before_57_days,29.11.2014,355,20:59,0.0,0.0,0.0,"29417,17282,20332",No_risk
24,31627.0,male,"47,3",L,Non_Verified,Heterosexual,Dominant,Women,66,before_386_days,30.11.2014,166,0:0,0.0,0.0,0.0,NaN,No_risk
25,31698.0,female,"29,7",A,Verified,bicurious,Submisive,Nobody,404,before_1_days,3.12.2014,332,9:39,0.0,3.0,11.0,"29417,42259,39854,44455,38169,9752,46324,18996...",No_risk
26,3377.0,male,"50,8",F,Non_Verified,Heterosexual,Switch,Nobody_but_maybe,20,before_212_days,16.8.2011,42,0:1,1.0,0.0,0.0,NaN,No_risk
27,34759.0,male,"26,8",C,Non_Verified,Heterosexual,Dominant,Women,0,before_1_days,20.4.2015,0,38:24,0.0,0.0,0.0,42882,No_risk
28,34980.0,female,"31,3",A,Non_Verified,Heterosexual,Submisive,Nobody_but_maybe,0,before_725_days,4.5.2015,0,0:0,0.0,0.0,0.0,NaN,No_risk
29,35266.0,male,"39,2",M,Non_Verified,Heterosexual,Switch,Women,0,before_11_days,20.5.2015,0,0:0,0.0,0.0,0.0,NaN,No_risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048553,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
sexWork_df = sexWork_df.dropna(axis=0, how='all')
sexWork_df.tail()

,User_ID,Gender,Age,Location,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Points_Rank,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_advertisments_posted,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
28826,9962.0,male,"27,2",J,Non_Verified,Heterosexual,Switch,Women,0,before_23_days,5.9.2012,0,0:3,1.0,0.0,0.0,NaN,unknown_risk
28827,9964.0,male,"46,4",J,Non_Verified,bicurious,Submisive,Men_and_Women,15,before_597_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28828,9966.0,male,"28,8",C,Non_Verified,Heterosexual,Submisive,Women,15,before_4_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28829,9968.0,male,"31,5",J,Non_Verified,bisexual,Submisive,Men,30,before_665_days,1.9.2012,0,2:54,4.0,0.0,0.0,NaN,unknown_risk
28830,998.0,female,"38,7",F,Non_Verified,Heterosexual,Dominant,Nobody,20,before_157_days,20.5.2010,0,0:9,0.0,0.0,1.0,NaN,unknown_risk

In [29]:
sexWork_df.to_csv('../../data/raw/cleaned_online_sex_work.csv', encoding='utf-8', index=False)

In [30]:
sexWork_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28831 entries, 0 to 28830
Data columns (total 18 columns):
User_ID                                28831 non-null float64
Gender                                 28827 non-null object
Age                                    28831 non-null object
Location                               28830 non-null object
Verification                           28831 non-null object
Sexual_orientation                     28830 non-null object
Sexual_polarity                        28830 non-null object
Looking_for                            28406 non-null object
Points_Rank                            28831 non-null object
Last_login                             28831 non-null object
Member_since                           28831 non-null object
Number_of_Comments_in_public_forum     28831 non-null object
Time_spent_chating_H:M                 28831 non-null object
Number_of_advertisments_posted         28831 non-null float64
Number_of_offline_meetings_attended    28831 non-null float64
Profile_pictures                       28831 non-null float64
Friends_ID_list                        3313 non-null object
Risk                                   28831 non-null object
dtypes: float64(4), object(14)
memory usage: 4.2+ MB

In [37]:
#Getting an idea of how many null values are in each column of the dataset
sexWork_nullColumns = sexWork_df.columns[sexWork_df.isnull().any()]
sexWork_df[sexWork_nullColumns].isnull().sum()

Gender                    4
Location                  1
Sexual_orientation        1
Sexual_polarity           1
Looking_for             425
Friends_ID_list       25518
dtype: int64

In [32]:
sexWork_df[sexWork_df.isnull().any(axis=1)]

,User_ID,Gender,Age,Location,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Points_Rank,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_advertisments_posted,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
6,1726.0,male,"36,7",B,Non_Verified,bicurious,Submisive,Women,18,before_1_days,16.10.2010,1,122:20,17.0,0.0,0.0,NaN,No_risk
14,19990.0,male,"36,8",E,Non_Verified,Heterosexual,Submisive,Women,0,before_62_days,28.7.2013,0,45:24,0.0,0.0,0.0,NaN,No_risk
15,20926.0,male,"30,9",A,Non_Verified,Heterosexual,Submisive,Nobody_but_maybe,15,before_1_days,2.9.2013,0,10:41,0.0,0.0,0.0,NaN,No_risk
17,22458.0,female,"48,6",L,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,236,before_1_days,5.11.2013,501,0:0,0.0,0.0,25.0,NaN,No_risk
19,25379.0,male,"35,3",A,Non_Verified,Heterosexual,Submisive,Women,18,before_6_days,4.3.2014,3,3:25,1.0,0.0,0.0,NaN,No_risk
21,27813.0,male,"35,3",A,Non_Verified,Heterosexual,Submisive,Nobody,0,before_15_days,24.6.2014,0,3:20,0.0,0.0,0.0,NaN,No_risk
24,31627.0,male,"47,3",L,Non_Verified,Heterosexual,Dominant,Women,66,before_386_days,30.11.2014,166,0:0,0.0,0.0,0.0,NaN,No_risk
26,3377.0,male,"50,8",F,Non_Verified,Heterosexual,Switch,Nobody_but_maybe,20,before_212_days,16.8.2011,42,0:1,1.0,0.0,0.0,NaN,No_risk
28,34980.0,female,"31,3",A,Non_Verified,Heterosexual,Submisive,Nobody_but_maybe,0,before_725_days,4.5.2015,0,0:0,0.0,0.0,0.0,NaN,No_risk
29,35266.0,male,"39,2",M,Non_Verified,Heterosexual,Switch,Women,0,before_11_days,20.5.2015,0,0:0,0.0,0.0,0.0,NaN,No_risk
32,3987.0,male,"28,1",L,Verified,Heterosexual,Switch,Women,226,before_9_days,17.11.2011,73,0:0,0.0,0.0,2.0,NaN,No_risk
33,40412.0,male,"24,6",E,Non_Verified,Heterosexual,Submisive,Nobody,0,before_4_days,27.2.2016,0,0:0,0.0,0.0,0.0,NaN,No_risk
36,43656.0,male,"54,3",L,Non_Verified,bisexual,Dominant,Women,32,before_3_days,26.8.2016,4,0:0,0.0,0.0,6.0,NaN,No_risk
37,44151.0,male,"29,9",G,Non_Verified,Heterosexual,Switch,NaN,58,before_5_days,19.9.2016,36,0:0,2.0,0.0,3.0,NaN,No_risk
42,46681.0,male,"42,6",E,Non_Verified,Heterosexual,Switch,Women,0,before_30_days,28.1.2017,0,0:31,0.0,0.0,0.0,NaN,No_risk
45,47917.0,male,"35,5",B,Non_Verified,Heterosexual,Dominant,Women,0,before_3_days,29.3.2017,0,0:25,0.0,0.0,0.0,NaN,No_risk
46,48294.0,male,24,A,Non_Verified,Heterosexual,Switch,Nobody_but_maybe,10,before_1_days,15.4.2017,8,0:0,0.0,0.0,2.0,NaN,No_risk
47,6035.0,male,"52,3",A,Non_Verified,Heterosexual,Submisive,Women,114,before_1_days,2.7.2012,120,6:46,1.0,0.0,0.0,NaN,No_risk
50,6418.0,male,41,F,Non_Verified,Heterosexual,Submisive,Women,0,before_1_days,5.7.2012,34,4:50,2.0,0.0,0.0,NaN,No_risk
57,12262.0,male,"35,7",A,Non_Verified,Heterosexual,Submisive,Women,0,before_4_days,17.11.2012,0,0:0,0.0,0.0,0.0,NaN,High_risk
59,1353.0,male,"49,6",A,Non_Verified,Heterosexual,Submisive,Nobody,15,before_11_days,9.8.2010,0,0:0,0.0,0.0,0.0,NaN,High_risk
61,15172.0,male,"52,3",E,Non_Verified,Heterosexual,Submisive,Nobody,0,before_424_days,10.2.2013,0,0:0,0.0,0.0,0.0,NaN,High_risk
62,17871.0,male,"27,3",F,Non_Verified,Heterosexual,Submisive,Women,15,before_1_days,12.5.2013,0,0:59,1.0,0.0,0.0,NaN,High_risk
65,22592.0,male,"35,2",B,Non_Verified,Heterosexual,Submisive,Women,0,before_1255_days,11.11.2013,0,0:0,0.0,0.0,0.0,NaN,High_risk
66,23282.0,male,"27,3",A,Non_Verified,bicurious,Submisive,Men_and_Women,28,before_4_days,11.12.2013,13,0:0,1.0,0.0,0.0,NaN,High_risk
70,34414.0,male,"34,3",A,Non_Verified,Heterosexual,Submisive,Women,25,before_1_days,1.4.2015,0,0:0,0.0,0.0,5.0,NaN,High_risk
72,34922.0,male,30,B,Verified,Heterosexual,Submisive,Nobody_but_maybe,471,before_6_days,2.5.2015,294,1:44,0.0,0.0,19.0,NaN,High_risk
73,35359.0,male,"36,1",A,Non_Verified,Heterosexual,Submisive,Women,48,before_3_days,24.5.2015,38,0:0,0.0,0.0,0.0,NaN,High_risk
74,39099.0,male,"34,5",J,Non_Verified,Heterosexual,Switch,Women,50,before_1_days,19.12.2015,0,0:0,1.0,0.0,1.0,NaN,High_risk
75,39386.0,male,"46,8",F,Non_Verified,Heterosexual,Switch,Women,55,before_3_days,3.1.2016,5,1:34,0.0,0.0,11.0,NaN,High_risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28800,9921.0,female,49,N,Non_Verified,bicurious,Submisive,Nobody,0,before_1698_days,4.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28801,9923.0,male,"46,3",H,Non_Verified,Heterosexual,Submisive,Nobody,0,before_1656_days,4.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28802,9925.0,female,"32,1",A,Non_Verified,bisexual,Dominant,Women,1,before_97_days,4.9.2012,1,0:0,1.0,0.0,1.0,NaN,unknown_risk
28803,9926.0,male,"45,6",A,Non_Verified,bicurious,Switch,Nobody,0,before_1697_days,4.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28804,9928.0,male,"36,1",E,Non_Verified,Heterosexual,Submisive,Nobody,0,before_1687_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28805,9929.0,male,"26,8",A,Non_Verified,Heterosexual,Switch,Nobody,15,before_1697_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28806,9931.0,male,"56,3",M,Non_Verified,Heterosexual,Switch,Nobody,0,before_1697_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28807,9932.0,male,"43,7",A,Non_Verified,Heterosexual,Submisive,Women,15,before_979_days,5.9.2012,0,1:51,0.0,0.0,0.0,NaN,unknown_risk
28808,9934.0,female,"40,9",G,Non_Verified,Heterosexual,Submisive,Nobody,0,before_1691_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28809,9937.0,male,"47,2",A,Non_Verified,Heterosexual,Dominant,Women,0,before_884_days,5.9.2012,0,0:1,0.0,0.0,0.0,NaN,unknown_risk
28810,9938.0,female,"44,7",A,Non_Verified,Heterosexual,Submisive,Nobody,0,before_1349_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28811,9939.0,male,"40,1",A,Non_Verified,Heterosexual,Switch,Nobody,0,before_1697_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28812,994.0,male,"32,7",S,Non_Verified,Heterosexual,Submisive,Women,15,before_205_days,19.5.2010,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28813,9940.0,male,"28,4",A,Non_Verified,Heterosexual,Dominant,Nobody,0,before_944_days,5.9.2012,0,0:0,1.0,0.0,0.0,NaN,unknown_risk
28814,9941.0,male,33,A,Verified,Heterosexual,Switch,Women,245,before_12_days,5.9.2012,0,0:0,1.0,0.0,1.0,NaN,unknown_risk
28815,9942.0,male,"26,8",A,Non_Verified,Heterosexual,Switch,Nobody,0,before_453_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28816,9943.0,male,"30,2",A,Non_Verified,Heterosexual,Dominant,Nobody,0,before_1697_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28817,9944.0,male,23,E,Non_Verified,bicurious,Submisive,Men,15,before_1510_days,5.9.2012,0,0:0,3.0,0.0,0.0,NaN,unknown_risk
28818,9945.0,male,"48,7",B,Non_Verified,Heterosexual,Dominant,Nobody,0,before_481_days,5.9.2012,0,0:4,2.0,0.0,0.0,NaN,unknown_risk
28819,9947.0,male,35,O,Non_Verified,Heterosexual,Submisive,Women,0,before_35_days,5.9.2012,0,0:0,1.0,0.0,0.0,NaN,unknown_risk
28820,9948.0,female,"41,7",G,Non_Verified,bisexual,Dominant,Nobody,0,before_1697_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28821,9950.0,male,"38,9",A,Non_Verified,Heterosexual,Submisive,Women,0,before_12_days,5.9.2012,0,0:0,1.0,0.0,0.0,NaN,unknown_risk
28822,9951.0,male,"32,4",A,Non_Verified,bisexual,Dominant,Men_and_Women,0,before_1515_days,5.9.2012,0,6:6,0.0,0.0,0.0,NaN,unknown_risk
28824,9960.0,male,"50,5",F,Non_Verified,Heterosexual,Submisive,Nobody,0,before_1688_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28825,9961.0,male,"43,9",A,Non_Verified,Heterosexual,Dominant,Women,15,before_42_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28826,9962.0,male,"27,2",J,Non_Verified,Heterosexual,Switch,Women,0,before_23_days,5.9.2012,0,0:3,1.0,0.0,0.0,NaN,unknown_risk
28827,9964.0,male,"46,4",J,Non_Verified,bicurious,Submisive,Men_and_Women,15,before_597_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28828,9966.0,male,"28,8",C,Non_Verified,Heterosexual,Submisive,Women,15,before_4_days,5.9.2012,0,0:0,0.0,0.0,0.0,NaN,unknown_risk
28829,9968.0,male,"31,5",J,Non_Verified,bisexual,Submisive,Men,30,before_665_days,1.9.2012,0,2:54,4.0,0.0,0.0,NaN,unknown_risk
28830,998.0,female,"38,7",F,Non_Verified,Heterosexual,Dominant,Nobody,20,before_157_days,20.5.2010,0,0:9,0.0,0.0,1.0,NaN,unknown_risk

## Reddit Thread

In [33]:
redditThread_df = pd.read_csv('../../data/raw/foreveralone.csv')
redditThread_df.tail()

,time,gender,sexuallity,age,income,race,bodyweight,virgin,prostitution_legal,pay_for_sex,friends,social_fear,depressed,what_help_from_others,attempt_suicide,employment,job_title,edu_level,improve_yourself_how
464,6/2/2016 5:04:24,Female,Straight,26,"$10,000 to $19,999",White non-Hispanic,Overweight,Yes,No,Yes but I haven't,10.0,Yes,No,"Set me up with a date, date coaching",No,Employed for wages,Consultant IT,Master’s degree,Joined a gym/go to the gym
465,6/3/2016 19:25:46,Male,Straight,31,"$30,000 to $39,999",White non-Hispanic,Normal weight,No,No,Yes but I haven't,10.0,No,No,I don't want help,No,Employed for wages,castor,"High school graduate, diploma or the equivalen...","Other exercise, join clubs/socual clubs/meet ups"
466,6/6/2016 1:36:55,Female,Straight,17,"$1 to $10,000",Asian,Normal weight,Yes,No,No,20.0,Yes,Yes,wingman/wingwoman,Yes,Employed for wages,receptionist,"Some high school, no diploma","Joined a gym/go to the gym, Other exercise, jo..."
467,8/14/2016 15:10:41,Male,Straight,18,$0,Asian,Obese,Yes,No,No,16.0,Yes,Yes,Set me up with a date,No,Out of work but not currently looking for work,Student,"High school graduate, diploma or the equivalen...","Joined a gym/go to the gym, Therapy"
468,9/4/2016 23:10:04,Male,Straight,28,"$40,000 to $49,999",White non-Hispanic,Normal weight,Yes,No,Yes but I haven't,3.0,Yes,Yes,"wingman/wingwoman, Set me up with a date, date...",No,Employed for wages,Scientist,Master’s degree,Therapy

In [34]:
redditThread_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 469 entries, 0 to 468
Data columns (total 19 columns):
time                     469 non-null object
gender                   469 non-null object
sexuallity               469 non-null object
age                      469 non-null int64
income                   469 non-null object
race                     469 non-null object
bodyweight               469 non-null object
virgin                   469 non-null object
prostitution_legal       469 non-null object
pay_for_sex              469 non-null object
friends                  469 non-null float64
social_fear              469 non-null object
depressed                469 non-null object
what_help_from_others    469 non-null object
attempt_suicide          469 non-null object
employment               469 non-null object
job_title                461 non-null object
edu_level                469 non-null object
improve_yourself_how     469 non-null object
dtypes: float64(1), int64(1), object(17)
memory usage: 69.7+ KB

In [38]:
#Getting an idea of how many null values are in each column of the dataset
redditThread_nullColumns = redditThread_df.columns[redditThread_df.isnull().any()]
redditThread_df[redditThread_nullColumns].isnull().sum()

job_title    8
dtype: int64

In [36]:
redditThread_df[redditThread_df.isnull().any(axis=1)]

,time,gender,sexuallity,age,income,race,bodyweight,virgin,prostitution_legal,pay_for_sex,friends,social_fear,depressed,what_help_from_others,attempt_suicide,employment,job_title,edu_level,improve_yourself_how
30,5/17/2016 21:08:26,Male,Straight,17,$0,Asian,Underweight,Yes,Yes,No,5.0,Yes,No,"wingman/wingwoman, Set me up with a date",No,A student,NaN,"Some high school, no diploma",None
54,5/17/2016 22:43:42,Male,Straight,18,$0,Black,Overweight,Yes,Yes,Yes but I haven't,0.0,Yes,No,I don't want help,No,A student,NaN,"High school graduate, diploma or the equivalen...",None
55,5/17/2016 22:44:08,Male,Straight,19,$0,White non-Hispanic,Underweight,Yes,No,Yes but I haven't,10.0,Yes,No,date coaching,No,Out of work but not currently looking for work,NaN,"Some college, no degree","Other exercise, join clubs/socual clubs/meet ups"
130,5/18/2016 1:55:46,Male,Straight,30,"$50,000 to $74,999",Mixed race,Underweight,No,No,No,12.0,Yes,Yes,Set me up with a date,No,Out of work but not currently looking for work,NaN,"Some college, no degree","Therapy, Other exercise"
170,5/18/2016 4:59:02,Male,Straight,23,$0,White non-Hispanic,Underweight,Yes,No,No,0.0,Yes,Yes,I don't want help,No,Out of work but not currently looking for work,NaN,Associate degree,None
352,5/19/2016 5:07:20,Male,Straight,24,$0,White non-Hispanic,Normal weight,No,Yes,Yes and I have,0.0,Yes,Yes,Set me up with a date,No,Out of work and looking for work,NaN,"High school graduate, diploma or the equivalen...","Joined a gym/go to the gym, Therapy, Other exe..."
371,5/20/2016 3:06:30,Male,Straight,14,$0,Half Asian half white,Normal weight,Yes,No,Yes but I haven't,1.0,Yes,Yes,I don't want help,No,A student,NaN,"Some high school, no diploma","Joined a gym/go to the gym, join clubs/socual ..."
372,5/20/2016 10:38:33,Male,Straight,22,$0,White non-Hispanic,Normal weight,Yes,No,Yes but I haven't,1.0,Yes,Yes,date coaching,No,Out of work but not currently looking for work,NaN,Trade/technical/vocational training,"Joined a gym/go to the gym, Therapy, join club..."