# 200_Prep_Datasets

This notebook contains our code illustrating the steps we undertook to prepare our datasets.

In [281]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
%matplotlib inline

In [282]:
sexWork_df = pd.read_csv('../../data/raw/cleaned_online_sex_work.csv')
sexWork_df.head()

,User_ID,Gender,Age,Location,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Points_Rank,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_advertisments_posted,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
0,10386.0,male,"34,6",A,Non_Verified,Homosexual,Switch,Men,50,before_10_days,17.9.2012,32,0:2,0.0,0.0,0.0,18260,No_risk
1,14.0,male,"32,2",J,Non_Verified,Heterosexual,Dominant,Women,518,before_1_days,1.11.2009,710,3:45,9.0,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk
2,16721.0,male,"33,6",K,Non_Verified,Heterosexual,Dominant,Women,150,before_3_days,1.4.2013,25,2:15,1.0,1.0,45.0,"19805,21721,19802",No_risk
3,16957.0,male,34,H,Non_Verified,Heterosexual,Dominant,Women,114,before_4_days,8.4.2013,107,359:22,1.0,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk
4,17125.0,male,"39,5",B,Non_Verified,Heterosexual,Dominant,Women,497,before_5_days,14.4.2013,600,0:21,0.0,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk

## Removal of unnecessary columns

In [283]:
cols_Of_Interest = [0, 3, 8, 13]
sexWork_df.drop(sexWork_df.columns[cols_Of_Interest], axis=1, inplace=True)
sexWork_df.head()

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,17.9.2012,32,0:2,0.0,0.0,18260,No_risk
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,1.11.2009,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,1.4.2013,25,2:15,1.0,45.0,"19805,21721,19802",No_risk
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,8.4.2013,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,14.4.2013,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk

In [284]:
sexWork_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28831 entries, 0 to 28830
Data columns (total 14 columns):
Gender                                 28827 non-null object
Age                                    28831 non-null object
Verification                           28831 non-null object
Sexual_orientation                     28830 non-null object
Sexual_polarity                        28830 non-null object
Looking_for                            28406 non-null object
Last_login                             28831 non-null object
Member_since                           28831 non-null object
Number_of_Comments_in_public_forum     28831 non-null object
Time_spent_chating_H:M                 28831 non-null object
Number_of_offline_meetings_attended    28831 non-null float64
Profile_pictures                       28831 non-null float64
Friends_ID_list                        3313 non-null object
Risk                                   28831 non-null object
dtypes: float64(2), object(12)
memory usage: 3.1+ MB

The columns "User ID", "Number_of_advertisements_posted", "Location", "Points_Rank" are removed from the dataset. We concluded, after careful planning that these columns would not be necessary for our analysis.

### Change Age to float

In [285]:
#replace all commas with dots
sexWork_df['Age'] = [x.replace(',', '.') for x in sexWork_df['Age']]

sexWork_df.head()

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,17.9.2012,32,0:2,0.0,0.0,18260,No_risk
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,1.11.2009,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,1.4.2013,25,2:15,1.0,45.0,"19805,21721,19802",No_risk
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,8.4.2013,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,14.4.2013,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk

In [286]:
sexWork_df.loc[[26871]] # A check carried out to ensure all commas were replaced with a full stop.

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
26871,male,25.2,Non_Verified,Heterosexual,Submisive,Nobody,before_69_days,7.7.2012,0,0:0,0.0,0.0,NaN,unknown_risk

In [287]:
#change all the ??? in Age to NaN
sexWork_df.at[1357, 'Age'] = np.nan
sexWork_df.at[4796, 'Age'] = np.nan
sexWork_df.at[5978, 'Age'] = np.nan
sexWork_df.at[8182, 'Age'] = np.nan
sexWork_df.at[26887, 'Age'] = np.nan
sexWork_df.at[27252, 'Age'] = np.nan

In [288]:
#convert to float
sexWork_df['Age'] = pd.to_numeric(sexWork_df['Age'])
#sexWork_df.head()

The ages were comma separated with the values after the comma representing the individuals age in months within that particular year e.g 32,8 - 32 years 8 months old. Although, if we needed to make a graph using the comma separated values, complications would arise. Thus the commas were replaced with a full stop in order to convert the age to a type and format that would be understood by the kernel.

There were a few rows with junk values which we converted to "NaN" as without doing so, the type conversion from object to float would have been impossible. We also wanted to avoid having to remove the rows hence the "NaN" insertions.

### Years of Membership - The conversion process to datetime

The conversion for this column was not as straightforward as expected. The column contained junk values that interferred with the "to_datetime" call. The next few cells contain the approach we used to resolve the problem.

In [118]:
membership_Dates = sexWork_df['Member_since']
membership_Dates.head()

0    17.9.2012
1    1.11.2009
2     1.4.2013
3     8.4.2013
4    14.4.2013
Name: Member_since, dtype: object

In [119]:
dates = []
for x in membership_Dates:
    month = x.split('.')
    dates.append(month)

for shortened in range(0, 5):
    print(len(dates[shortened]))

3
3
3
3
3

Considering the dates were initially seperated by dots, a split on the dot was carried out on the column in order to ensure that each list created from every split contained 3 values, seeing as dates are in the Day/Month/Year format.

In [120]:
for x in membership_Dates:
    month = x.split('.')
    if(len(month)) < 3:
        print(month)
invalid_Dates = len(month)

['0,278159722']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']

Lists containing less than 3 values are searched for and if any are found they prove to be the dates preventing the datetie conversion

In [121]:
sexWork_df = sexWork_df[(sexWork_df['Member_since'] != 'dnes')]
sexWork_df.reset_index(drop=True)
sexWork_df.shape

(28820, 14)

In [122]:
sexWork_df[sexWork_df['Member_since'].str.contains('0.278159722')]

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
6369,male,31.7,Verified,Heterosexual,Switch,Nobody_but_maybe,before_1_days,"0,278159722",83,0:0,0.0,0.0,"1,1160,17282,19248,225",unknown_risk

In [123]:
sexWork_df = sexWork_df.drop(sexWork_df.index[[6369]])
sexWork_df.shape

(28819, 14)

In [124]:
sexWork_df['Member_since'] = pd.to_datetime(sexWork_df['Member_since'])
sexWork_df.head()

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk
3,male,34.0,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk

### Time Spent Chatting - The conversion process to datetime

In [125]:
#expands hours and minutes into two columns
sexWork_df[['Hours','Minutes']] = sexWork_df['Time_spent_chating_H:M'].str.split(':', expand=True)
#accounts for hour anomaly
sexWork_df[['Expanded_1','Expanded_2']] = sexWork_df['Hours'].str.split(' ', expand=True)
#fills the new 'None' values with empty space rather than NaN
sexWork_df['Expanded_2'].fillna(value='', inplace=True)

sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Expanded_1,Expanded_2
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,0,2,0,
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,3,45,3,
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,2,15,2,
3,male,34.0,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,359,22,359,
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,0,21,0,
5,female,47.8,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,1 436,52,1,436
6,male,36.7,Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,122,20,122,
7,male,51.0,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,0,5,0,
8,female,29.5,Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,84,19,84,
9,male,28.0,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,3,23,3,

In [126]:
#combine the two together again but without the initial space
sexWork_df['Hours'] = sexWork_df['Expanded_1'] + sexWork_df['Expanded_2']
#remove the unnecessary columns now that we're finished with them
sexWork_df.drop(['Expanded_1', 'Expanded_2'], axis=1, inplace = True)

sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,0,2
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,3,45
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,2,15
3,male,34.0,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,359,22
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,0,21
5,female,47.8,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,1436,52
6,male,36.7,Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,122,20
7,male,51.0,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,0,5
8,female,29.5,Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,84,19
9,male,28.0,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,3,23

In [127]:
#adds a seconds column for timedelta purposes
sexWork_df['Seconds'] = "00"
#fills in zeros for minutes
sexWork_df['Minutes'] = sexWork_df['Minutes'].astype(str).str.zfill(2)
#save the old hour format for day conversion
sexWork_df['Old_hours'] = sexWork_df['Hours']

sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,0,02,00,0
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,3,45,00,3
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,2,15,00,2
3,male,34.0,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,359,22,00,359
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,0,21,00,0
5,female,47.8,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,1436,52,00,1436
6,male,36.7,Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,122,20,00,122
7,male,51.0,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,0,05,00,0
8,female,29.5,Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,84,19,00,84
9,male,28.0,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,3,23,00,3

There were a lot of values in this column whose numbers were separated by whitespace. We didn't split on the whitespace as the objective was to remove the spaces to form whole numbers e.g 1 436 - 1436. So we expanded the values putting them in columns of their own in order to combine them through column concatenation.

#### Fix Hours

In [128]:
hours = sexWork_df['Hours'].astype(int)
remaining_hours = [x if x < 24 else int(((x/24)%1)*24) for x in hours]

In [129]:
#places properly calculated hours in the Hours column
sexWork_df['Hours'] = remaining_hours
sexWork_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28819 entries, 0 to 28830
Data columns (total 18 columns):
Gender                                 28815 non-null object
Age                                    28813 non-null float64
Verification                           28819 non-null object
Sexual_orientation                     28818 non-null object
Sexual_polarity                        28818 non-null object
Looking_for                            28395 non-null object
Last_login                             28819 non-null object
Member_since                           28819 non-null datetime64[ns]
Number_of_Comments_in_public_forum     28819 non-null object
Time_spent_chating_H:M                 28819 non-null object
Number_of_offline_meetings_attended    28819 non-null float64
Profile_pictures                       28819 non-null float64
Friends_ID_list                        3312 non-null object
Risk                                   28819 non-null object
Hours                                  28819 non-null int64
Minutes                                28819 non-null object
Seconds                                28819 non-null object
Old_hours                              28819 non-null object
dtypes: datetime64[ns](1), float64(3), int64(1), object(13)
memory usage: 4.2+ MB

In [130]:
#changes column type to string
sexWork_df['Hours'] = sexWork_df['Hours'].astype(str)
sexWork_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28819 entries, 0 to 28830
Data columns (total 18 columns):
Gender                                 28815 non-null object
Age                                    28813 non-null float64
Verification                           28819 non-null object
Sexual_orientation                     28818 non-null object
Sexual_polarity                        28818 non-null object
Looking_for                            28395 non-null object
Last_login                             28819 non-null object
Member_since                           28819 non-null datetime64[ns]
Number_of_Comments_in_public_forum     28819 non-null object
Time_spent_chating_H:M                 28819 non-null object
Number_of_offline_meetings_attended    28819 non-null float64
Profile_pictures                       28819 non-null float64
Friends_ID_list                        3312 non-null object
Risk                                   28819 non-null object
Hours                                  28819 non-null object
Minutes                                28819 non-null object
Seconds                                28819 non-null object
Old_hours                              28819 non-null object
dtypes: datetime64[ns](1), float64(3), object(14)
memory usage: 4.2+ MB

In [131]:
#fills in zeros for hours
sexWork_df['Hours'] = sexWork_df['Hours'].astype(str).str.zfill(2)

sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,00,02,00,0
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,03,45,00,3
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,02,15,00,2
3,male,34.0,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,23,22,00,359
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,00,21,00,0
5,female,47.8,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,20,52,00,1436
6,male,36.7,Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,01,20,00,122
7,male,51.0,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,00,05,00,0
8,female,29.5,Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,12,19,00,84
9,male,28.0,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,03,23,00,3

#### Add Days

In [132]:
days = sexWork_df['Old_hours'].astype(int)
calculated_days = [0 if x < 24 else (x//24) for x in days]

In [133]:
#places properly calculated days in the new Days column
sexWork_df['Days'] = calculated_days

In [134]:
#changes column type to string
sexWork_df['Days'] = sexWork_df['Days'].astype(str)
sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours,Days
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,00,02,00,0,0
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,03,45,00,3,0
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,02,15,00,2,0
3,male,34.0,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,23,22,00,359,14
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,00,21,00,0,0
5,female,47.8,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,20,52,00,1436,59
6,male,36.7,Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,01,20,00,122,5
7,male,51.0,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,00,05,00,0,0
8,female,29.5,Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,12,19,00,84,3
9,male,28.0,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,03,23,00,3,0

In [135]:
#fills in zeros for hours
sexWork_df['Days'] = sexWork_df['Days'].astype(str).str.zfill(2)

sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours,Days
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,00,02,00,0,00
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,03,45,00,3,00
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,02,15,00,2,00
3,male,34.0,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,23,22,00,359,14
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,00,21,00,0,00
5,female,47.8,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,20,52,00,1436,59
6,male,36.7,Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,01,20,00,122,05
7,male,51.0,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,00,05,00,0,00
8,female,29.5,Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,12,19,00,84,03
9,male,28.0,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,03,23,00,3,00

In [136]:
sexWork_df['Hours'] = sexWork_df['Hours'].astype(int)
sexWork_df['Minutes'] = sexWork_df['Minutes'].astype(int)
sexWork_df['Seconds'] = sexWork_df['Seconds'].astype(int)

In [137]:
sexWork_df['Total_chat_time'] = pd.to_timedelta(sexWork_df['Hours']*3600 + sexWork_df['Minutes']*60 + sexWork_df['Seconds'], unit='s')
sexWork_df.head()

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours,Days,Total_chat_time
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,0,2,0,0,00,00:02:00
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,3,45,0,3,00,03:45:00
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,2,15,0,2,00,02:15:00
3,male,34.0,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,23,22,0,359,14,23:22:00
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,0,21,0,0,00,00:21:00

In [ ]:
sexWork_df.drop(['Hours', 'Minutes', 'Seconds', 'Old_hours'], axis=1, inplace=True)

## Representing the number of Friends ID as a count

In [138]:
#splitting on a comma to create lists within the dataframe while ignoring nan Values
sexWork_df['Friends_ID_list'] = sexWork_df['Friends_ID_list'].apply(lambda x: x.split(',') if not pd.isnull(x) else np.nan)
sexWork_df['Friends_ID_list'] = sexWork_df['Friends_ID_list'].str.len()
sexWork_df['Friends'] = sexWork_df['Friends_ID_list']

In [139]:
sexWork_df.drop(['Friends_ID_list'], axis=1, inplace=True)

In [140]:
sexWork_df.head(5)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Risk,Days,Total_chat_time,Friends
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,No_risk,00,00:02:00,1.0
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,No_risk,00,03:45:00,7.0
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,No_risk,00,02:15:00,3.0
3,male,34.0,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,No_risk,14,23:22:00,12.0
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,No_risk,00,00:21:00,35.0

In [141]:
sexWork_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28819 entries, 0 to 28830
Data columns (total 16 columns):
Gender                                 28815 non-null object
Age                                    28813 non-null float64
Verification                           28819 non-null object
Sexual_orientation                     28818 non-null object
Sexual_polarity                        28818 non-null object
Looking_for                            28395 non-null object
Last_login                             28819 non-null object
Member_since                           28819 non-null datetime64[ns]
Number_of_Comments_in_public_forum     28819 non-null object
Time_spent_chating_H:M                 28819 non-null object
Number_of_offline_meetings_attended    28819 non-null float64
Profile_pictures                       28819 non-null float64
Risk                                   28819 non-null object
Days                                   28819 non-null object
Total_chat_time                        28819 non-null timedelta64[ns]
Friends                                3312 non-null float64
dtypes: datetime64[ns](1), float64(4), object(10), timedelta64[ns](1)
memory usage: 3.7+ MB

## Fixing values in 'comments' column

In [142]:
sexWork_df[['Expanded_1','Expanded_2']] = sexWork_df['Number_of_Comments_in_public_forum'].str.split(' ', expand=True)
#fills the new 'None' values with empty space rather than NaN
sexWork_df['Expanded_2'].fillna(value='', inplace=True)

In [143]:
#combine the two together again but without the initial space
sexWork_df['Number_of_Comments_in_public_forum'] = sexWork_df['Expanded_1'] + sexWork_df['Expanded_2']
#remove the unnecessary columns now that we're finished with them
sexWork_df.drop(['Expanded_1', 'Expanded_2'], axis=1, inplace = True)

In [144]:
sexWork_df['Number_of_Comments_in_public_forum'] = sexWork_df['Number_of_Comments_in_public_forum'].astype(int)

In [145]:
sexWork_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28819 entries, 0 to 28830
Data columns (total 16 columns):
Gender                                 28815 non-null object
Age                                    28813 non-null float64
Verification                           28819 non-null object
Sexual_orientation                     28818 non-null object
Sexual_polarity                        28818 non-null object
Looking_for                            28395 non-null object
Last_login                             28819 non-null object
Member_since                           28819 non-null datetime64[ns]
Number_of_Comments_in_public_forum     28819 non-null int32
Time_spent_chating_H:M                 28819 non-null object
Number_of_offline_meetings_attended    28819 non-null float64
Profile_pictures                       28819 non-null float64
Risk                                   28819 non-null object
Days                                   28819 non-null object
Total_chat_time                        28819 non-null timedelta64[ns]
Friends                                3312 non-null float64
dtypes: datetime64[ns](1), float64(4), int32(1), object(9), timedelta64[ns](1)
memory usage: 3.6+ MB

## Futher garbage value checks

To ensure no other garbage values exist in some of the columns, the "unique" call is used to inspect the contents of each column.

In [146]:
sexWork_df['Gender'].unique()

array(['male', 'female', nan], dtype=object)

In [147]:
sexWork_df['Sexual_orientation'].unique()

array(['Homosexual', 'Heterosexual', 'bicurious', 'bisexual', nan], dtype=object)

In [148]:
sexWork_df['Sexual_polarity'].unique()

array(['Switch', 'Dominant', 'Submisive', nan], dtype=object)

In [149]:
sexWork_df['Looking_for'].unique()

array(['Men', 'Women', 'Nobody_but_maybe', 'Nobody', 'Men_and_Women', nan], dtype=object)

In [150]:
sexWork_df['Risk'].unique()

array(['No_risk', 'High_risk', 'unknown_risk'], dtype=object)

In [151]:
sexWork_df['Risk'].unique()

array(['No_risk', 'High_risk', 'unknown_risk'], dtype=object)

In [87]:
#index=False to get rid of Unnamed: 0 column in new csv
sexWork_df.to_csv('../../data/raw/prepped_online_sex_work.csv', encoding='utf-8', index=False)

In [152]:
sexWork_df

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Risk,Days,Total_chat_time,Friends
0,male,34.6,Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,No_risk,00,00:02:00,1.0
1,male,32.2,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,No_risk,00,03:45:00,7.0
2,male,33.6,Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,No_risk,00,02:15:00,3.0
3,male,34.0,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,No_risk,14,23:22:00,12.0
4,male,39.5,Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,No_risk,00,00:21:00,35.0
5,female,47.8,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,No_risk,59,20:52:00,33.0
6,male,36.7,Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,No_risk,05,01:20:00,NaN
7,male,51.0,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,No_risk,00,00:05:00,1.0
8,female,29.5,Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,No_risk,03,12:19:00,32.0
9,male,28.0,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,No_risk,00,03:23:00,3.0
10,male,42.9,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-07-07,0,2:2,0.0,0.0,No_risk,00,02:02:00,4.0
11,female,45.4,Non_Verified,Heterosexual,Submisive,Nobody,before_3_days,2013-07-17,47,331:18,11.0,0.0,No_risk,13,18:18:00,31.0
12,male,36.1,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-07-19,0,139:53,0.0,0.0,No_risk,05,19:53:00,2.0
13,male,42.0,Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-07-20,51,508:8,5.0,0.0,No_risk,21,04:08:00,26.0
14,male,36.8,Non_Verified,Heterosexual,Submisive,Women,before_62_days,2013-07-28,0,45:24,0.0,0.0,No_risk,01,21:24:00,NaN
15,male,30.9,Non_Verified,Heterosexual,Submisive,Nobody_but_maybe,before_1_days,2013-02-09,0,10:41,0.0,0.0,No_risk,00,10:41:00,NaN
16,male,33.9,Verified,Heterosexual,Dominant,Women,before_3_days,2013-09-26,59,0:0,0.0,0.0,No_risk,00,00:00:00,1.0
17,female,48.6,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-05-11,501,0:0,0.0,25.0,No_risk,00,00:00:00,NaN
18,male,56.2,Non_Verified,Heterosexual,Submisive,Women,before_315_days,2014-10-01,68,115:34,0.0,0.0,No_risk,04,19:34:00,2.0
19,male,35.3,Non_Verified,Heterosexual,Submisive,Women,before_6_days,2014-04-03,3,3:25,0.0,0.0,No_risk,00,03:25:00,NaN
20,female,23.8,Non_Verified,bisexual,Submisive,Nobody,before_3_days,2014-06-24,247,1:25,0.0,5.0,No_risk,00,01:25:00,1.0
21,male,35.3,Non_Verified,Heterosexual,Submisive,Nobody,before_15_days,2014-06-24,0,3:20,0.0,0.0,No_risk,00,03:20:00,NaN
22,male,36.7,Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2011-06-14,845,0:4,0.0,0.0,No_risk,00,00:04:00,1.0
23,male,39.3,Verified,Heterosexual,Dominant,Nobody_but_maybe,before_57_days,2014-11-29,355,20:59,0.0,0.0,No_risk,00,20:59:00,3.0
24,male,47.3,Non_Verified,Heterosexual,Dominant,Women,before_386_days,2014-11-30,166,0:0,0.0,0.0,No_risk,00,00:00:00,NaN
25,female,29.7,Verified,bicurious,Submisive,Nobody,before_1_days,2014-03-12,332,9:39,3.0,11.0,No_risk,00,09:39:00,11.0
26,male,50.8,Non_Verified,Heterosexual,Switch,Nobody_but_maybe,before_212_days,2011-08-16,42,0:1,0.0,0.0,No_risk,00,00:01:00,NaN
27,male,26.8,Non_Verified,Heterosexual,Dominant,Women,before_1_days,2015-04-20,0,38:24,0.0,0.0,No_risk,01,13:24:00,1.0
28,female,31.3,Non_Verified,Heterosexual,Submisive,Nobody_but_maybe,before_725_days,2015-04-05,0,0:0,0.0,0.0,No_risk,00,00:00:00,NaN
29,male,39.2,Non_Verified,Heterosexual,Switch,Women,before_11_days,2015-05-20,0,0:0,0.0,0.0,No_risk,00,00:00:00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28801,male,46.3,Non_Verified,Heterosexual,Submisive,Nobody,before_1656_days,2012-04-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28802,female,32.1,Non_Verified,bisexual,Dominant,Women,before_97_days,2012-04-09,1,0:0,0.0,1.0,unknown_risk,00,00:00:00,NaN
28803,male,45.6,Non_Verified,bicurious,Switch,Nobody,before_1697_days,2012-04-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28804,male,36.1,Non_Verified,Heterosexual,Submisive,Nobody,before_1687_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28805,male,26.8,Non_Verified,Heterosexual,Switch,Nobody,before_1697_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28806,male,56.3,Non_Verified,Heterosexual,Switch,Nobody,before_1697_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28807,male,43.7,Non_Verified,Heterosexual,Submisive,Women,before_979_days,2012-05-09,0,1:51,0.0,0.0,unknown_risk,00,01:51:00,NaN
28808,female,40.9,Non_Verified,Heterosexual,Submisive,Nobody,before_1691_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28809,male,47.2,Non_Verified,Heterosexual,Dominant,Women,before_884_days,2012-05-09,0,0:1,0.0,0.0,unknown_risk,00,00:01:00,NaN
28810,female,44.7,Non_Verified,Heterosexual,Submisive,Nobody,before_1349_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28811,male,40.1,Non_Verified,Heterosexual,Switch,Nobody,before_1697_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28812,male,32.7,Non_Verified,Heterosexual,Submisive,Women,before_205_days,2010-05-19,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28813,male,28.4,Non_Verified,Heterosexual,Dominant,Nobody,before_944_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28814,male,33.0,Verified,Heterosexual,Switch,Women,before_12_days,2012-05-09,0,0:0,0.0,1.0,unknown_risk,00,00:00:00,NaN
28815,male,26.8,Non_Verified,Heterosexual,Switch,Nobody,before_453_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28816,male,30.2,Non_Verified,Heterosexual,Dominant,Nobody,before_1697_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28817,male,23.0,Non_Verified,bicurious,Submisive,Men,before_1510_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28818,male,48.7,Non_Verified,Heterosexual,Dominant,Nobody,before_481_days,2012-05-09,0,0:4,0.0,0.0,unknown_risk,00,00:04:00,NaN
28819,male,35.0,Non_Verified,Heterosexual,Submisive,Women,before_35_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28820,female,41.7,Non_Verified,bisexual,Dominant,Nobody,before_1697_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28821,male,38.9,Non_Verified,Heterosexual,Submisive,Women,before_12_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28822,male,32.4,Non_Verified,bisexual,Dominant,Men_and_Women,before_1515_days,2012-05-09,0,6:6,0.0,0.0,unknown_risk,00,06:06:00,NaN
28823,male,58.5,Non_Verified,Heterosexual,Dominant,Women,before_171_days,2012-05-09,0,5:58,0.0,0.0,unknown_risk,00,05:58:00,13.0
28824,male,50.5,Non_Verified,Heterosexual,Submisive,Nobody,before_1688_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28825,male,43.9,Non_Verified,Heterosexual,Dominant,Women,before_42_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28826,male,27.2,Non_Verified,Heterosexual,Switch,Women,before_23_days,2012-05-09,0,0:3,0.0,0.0,unknown_risk,00,00:03:00,NaN
28827,male,46.4,Non_Verified,bicurious,Submisive,Men_and_Women,before_597_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28828,male,28.8,Non_Verified,Heterosexual,Submisive,Women,before_4_days,2012-05-09,0,0:0,0.0,0.0,unknown_risk,00,00:00:00,NaN
28829,male,31.5,Non_Verified,bisexual,Submisive,Men,before_665_days,2012-01-09,0,2:54,0.0,0.0,unknown_risk,00,02:54:00,NaN
28830,female,38.7,Non_Verified,Heterosexual,Dominant,Nobody,before_157_days,2010-05-20,0,0:9,0.0,1.0,unknown_risk,00,00:09:00,NaN

# Forever Alone

In [88]:
redditThread_df = pd.read_csv('../../data/raw/foreveralone.csv')
redditThread_df.head()

,time,gender,sexuallity,age,income,race,bodyweight,virgin,prostitution_legal,pay_for_sex,friends,social_fear,depressed,what_help_from_others,attempt_suicide,employment,job_title,edu_level,improve_yourself_how
0,5/17/2016 20:04:18,Male,Straight,35,"$30,000 to $39,999",White non-Hispanic,Normal weight,Yes,No,No,0.0,Yes,Yes,"wingman/wingwoman, Set me up with a date",Yes,Employed for wages,mechanical drafter,Associate degree,None
1,5/17/2016 20:04:30,Male,Bisexual,21,"$1 to $10,000",White non-Hispanic,Underweight,Yes,No,No,0.0,Yes,Yes,"wingman/wingwoman, Set me up with a date, date...",No,Out of work and looking for work,-,"Some college, no degree",join clubs/socual clubs/meet ups
2,5/17/2016 20:04:58,Male,Straight,22,$0,White non-Hispanic,Overweight,Yes,No,No,10.0,Yes,Yes,I don't want help,No,Out of work but not currently looking for work,unemployed,"Some college, no degree",Other exercise
3,5/17/2016 20:08:01,Male,Straight,19,"$1 to $10,000",White non-Hispanic,Overweight,Yes,Yes,No,8.0,Yes,Yes,date coaching,No,A student,student,"Some college, no degree",Joined a gym/go to the gym
4,5/17/2016 20:08:04,Male,Straight,23,"$30,000 to $39,999",White non-Hispanic,Overweight,No,No,Yes and I have,10.0,No,Yes,I don't want help,No,Employed for wages,Factory worker,"High school graduate, diploma or the equivalen...",None

In [89]:
cols_Of_Interest_Reddit = [0, 4, 12, 13, 14, 15, 16, 18]
redditThread_df.drop(redditThread_df.columns[cols_Of_Interest_Reddit], axis=1, inplace=True)
redditThread_df.head()

,gender,sexuallity,age,race,bodyweight,virgin,prostitution_legal,pay_for_sex,friends,social_fear,edu_level
0,Male,Straight,35,White non-Hispanic,Normal weight,Yes,No,No,0.0,Yes,Associate degree
1,Male,Bisexual,21,White non-Hispanic,Underweight,Yes,No,No,0.0,Yes,"Some college, no degree"
2,Male,Straight,22,White non-Hispanic,Overweight,Yes,No,No,10.0,Yes,"Some college, no degree"
3,Male,Straight,19,White non-Hispanic,Overweight,Yes,Yes,No,8.0,Yes,"Some college, no degree"
4,Male,Straight,23,White non-Hispanic,Overweight,No,No,Yes and I have,10.0,No,"High school graduate, diploma or the equivalen..."

In [90]:
redditThread_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 469 entries, 0 to 468
Data columns (total 11 columns):
gender                469 non-null object
sexuallity            469 non-null object
age                   469 non-null int64
race                  469 non-null object
bodyweight            469 non-null object
virgin                469 non-null object
prostitution_legal    469 non-null object
pay_for_sex           469 non-null object
friends               469 non-null float64
social_fear           469 non-null object
edu_level             469 non-null object
dtypes: float64(1), int64(1), object(9)
memory usage: 40.4+ KB

In [91]:
redditThread_df = redditThread_df.rename(columns={"sexuallity": "sexuality"})

In [92]:
redditThread_df['race'].unique() #checking for junk values or duplicates

array(['White non-Hispanic', 'Hispanic (of any race)', 'Asian',
       'white and asian', 'caucasian', 'Black', 'Middle Eastern',
       'half Arab', 'Mixed race', 'Pakistani', 'helicopterkin', 'Turkish',
       'Indian', 'Native american', 'Mixed', 'mixed', 'Mixed white/asian',
       'indian', 'Multi', 'Native American mix', 'North African',
       'Half Asian half white', 'White and Native American',
       'First two answers. Gender is androgyne, not male; sexuality is asexual, not bi.',
       'European'], dtype=object)

In [93]:
redditThread_df[redditThread_df['race'].str.contains('mixed')] #duplicates on 'mixed' cus of different cases

,gender,sexuality,age,race,bodyweight,virgin,prostitution_legal,pay_for_sex,friends,social_fear,edu_level
266,Female,Straight,26,mixed,Normal weight,Yes,No,No,0.0,Yes,"High school graduate, diploma or the equivalen..."

In [94]:
redditThread_df.at[266, 'race'] = 'Mixed' #altering the value of mixed at it's index since. Hard coded it as it was just one duplicate

In [95]:
redditThread_df[redditThread_df['race'].str.contains('indian')]

,gender,sexuality,age,race,bodyweight,virgin,prostitution_legal,pay_for_sex,friends,social_fear,edu_level
301,Male,Straight,21,indian,Overweight,Yes,No,No,0.0,No,"Some college, no degree"

In [96]:
redditThread_df.at[301, 'race'] = 'Indian'

In [97]:
redditThread_df['race'].unique()

array(['White non-Hispanic', 'Hispanic (of any race)', 'Asian',
       'white and asian', 'caucasian', 'Black', 'Middle Eastern',
       'half Arab', 'Mixed race', 'Pakistani', 'helicopterkin', 'Turkish',
       'Indian', 'Native american', 'Mixed', 'Mixed white/asian', 'Multi',
       'Native American mix', 'North African', 'Half Asian half white',
       'White and Native American',
       'First two answers. Gender is androgyne, not male; sexuality is asexual, not bi.',
       'European'], dtype=object)

In [98]:
#answer for race here doesn't seem valid.. are we keeping it? I feel it'll affect our data.
redditThread_df[redditThread_df['race'].str.contains('First two answers. Gender is androgyne, not male; sexuality is asexual, not bi.')]

,gender,sexuality,age,race,bodyweight,virgin,prostitution_legal,pay_for_sex,friends,social_fear,edu_level
414,Male,Bisexual,26,"First two answers. Gender is androgyne, not ma...",Normal weight,No,No,No,0.0,Yes,Bachelor’s degree

In [99]:
#fill in row with data provided by user from the anomaly in the'race' column
redditThread_df.at[414, 'gender'] = 'Androgyne'
redditThread_df.at[414, 'sexuality'] = 'Asexual'

In [100]:
redditThread_df.at[414, 'race'] = np.nan

In [101]:
redditThread_df.loc[[414]]

,gender,sexuality,age,race,bodyweight,virgin,prostitution_legal,pay_for_sex,friends,social_fear,edu_level
414,Androgyne,Asexual,26,NaN,Normal weight,No,No,No,0.0,Yes,Bachelor’s degree

### Change column type

In [102]:
redditThread_df['friends'] = redditThread_df['friends'].astype(int)

In [103]:
redditThread_df['social_fear'] = redditThread_df['social_fear'].astype(bool)

In [104]:
redditThread_df['virgin'] = redditThread_df['virgin'].astype(bool)

In [105]:
redditThread_df['prostitution_legal'] = redditThread_df['prostitution_legal'].astype(bool)

In [106]:
redditThread_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 469 entries, 0 to 468
Data columns (total 11 columns):
gender                469 non-null object
sexuality             469 non-null object
age                   469 non-null int64
race                  468 non-null object
bodyweight            469 non-null object
virgin                469 non-null bool
prostitution_legal    469 non-null bool
pay_for_sex           469 non-null object
friends               469 non-null int32
social_fear           469 non-null bool
edu_level             469 non-null object
dtypes: bool(3), int32(1), int64(1), object(6)
memory usage: 28.9+ KB

In [107]:
redditThread_df.to_csv('../../data/raw/prepped_foreveralone.csv', encoding='utf-8', index=False)