# 200_Prep_Datasets

This notebook contains our code illustrating the steps we undertook to prepare our datasets.

In [352]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
%matplotlib inline

In [353]:
sexWork_df = pd.read_csv('../../data/raw/cleaned_online_sex_work.csv')
sexWork_df.head()

,Unnamed: 0,User_ID,Gender,Age,Location,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Points_Rank,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_advertisments_posted,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
0,0,10386.0,male,"34,6",A,Non_Verified,Homosexual,Switch,Men,50,before_10_days,17.9.2012,32,0:2,0.0,0.0,0.0,18260,No_risk
1,1,14.0,male,"32,2",J,Non_Verified,Heterosexual,Dominant,Women,518,before_1_days,1.11.2009,710,3:45,9.0,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk
2,2,16721.0,male,"33,6",K,Non_Verified,Heterosexual,Dominant,Women,150,before_3_days,1.4.2013,25,2:15,1.0,1.0,45.0,"19805,21721,19802",No_risk
3,3,16957.0,male,34,H,Non_Verified,Heterosexual,Dominant,Women,114,before_4_days,8.4.2013,107,359:22,1.0,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk
4,4,17125.0,male,"39,5",B,Non_Verified,Heterosexual,Dominant,Women,497,before_5_days,14.4.2013,600,0:21,0.0,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk

## Removal of unnecessary columns

In [354]:
cols_Of_Interest = [0, 1, 4, 9, 14]
sexWork_df.drop(sexWork_df.columns[cols_Of_Interest], axis=1, inplace=True)
sexWork_df.head()

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,17.9.2012,32,0:2,0.0,0.0,18260,No_risk
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,1.11.2009,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,1.4.2013,25,2:15,1.0,45.0,"19805,21721,19802",No_risk
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,8.4.2013,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,14.4.2013,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk

In [355]:
sexWork_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28831 entries, 0 to 28830
Data columns (total 14 columns):
Gender                                 28827 non-null object
Age                                    28831 non-null object
Verification                           28831 non-null object
Sexual_orientation                     28830 non-null object
Sexual_polarity                        28830 non-null object
Looking_for                            28406 non-null object
Last_login                             28831 non-null object
Member_since                           28831 non-null object
Number_of_Comments_in_public_forum     28831 non-null object
Time_spent_chating_H:M                 28831 non-null object
Number_of_offline_meetings_attended    28831 non-null float64
Profile_pictures                       28831 non-null float64
Friends_ID_list                        3313 non-null object
Risk                                   28831 non-null object
dtypes: float64(2), object(12)
memory usage: 3.1+ MB

### Years of Membership - The conversion process to datetime

The conversion for this column was not as straightforward as expected. The column contained junk values that interferred with the "to_datetime" call. The next few cells contain the approach we used to resolve the problem.

In [356]:
membership_Dates = sexWork_df['Member_since']
membership_Dates.head()

0    17.9.2012
1    1.11.2009
2     1.4.2013
3     8.4.2013
4    14.4.2013
Name: Member_since, dtype: object

Considering the dates were initially seperated by dots, a split on the dot was carried out on the column in order to ensure that each list created from every split contained 3 values, seeing as dates are in the Day/Month/Year format.

In [357]:
dates = []
for x in membership_Dates:
    month = x.split('.')
    dates.append(month)

for shortened in range(0, 5):
    print(len(dates[shortened]))

3
3
3
3
3

Lists containing less than 3 values are searched for and if any are found they prove to be the dates preventing the datetie conversion

In [358]:
for x in membership_Dates:
    month = x.split('.')
    if(len(month)) < 3:
        print(month)
invalid_Dates = len(month)

['0,278159722']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']
['dnes']

In [359]:
sexWork_df = sexWork_df[(sexWork_df['Member_since'] != 'dnes')]
sexWork_df.shape

(28820, 14)

In [360]:
sexWork_df[sexWork_df['Member_since'].str.contains('0.278159722')]

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
6369,male,"31,7",Verified,Heterosexual,Switch,Nobody_but_maybe,before_1_days,"0,278159722",83,0:0,0.0,0.0,"1,1160,17282,19248,225",unknown_risk

In [361]:
sexWork_df = sexWork_df.drop(sexWork_df.index[[6369]])
sexWork_df.shape

(28819, 14)

In [362]:
sexWork_df['Member_since'] = pd.to_datetime(sexWork_df['Member_since'])
sexWork_df.head()

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk

### Time Spent Chatting - The conversion process to datetime

In [363]:
#expands hours and minutes into two columns
sexWork_df[['Hours','Minutes']] = sexWork_df['Time_spent_chating_H:M'].str.split(':', expand=True)
#accounts for hour anomaly
sexWork_df[['Expanded_1','Expanded_2']] = sexWork_df['Hours'].str.split(' ', expand=True)
#fills the new 'None' values with empty space rather than NaN
sexWork_df['Expanded_2'].fillna(value='', inplace=True)

sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Expanded_1,Expanded_2
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,0,2,0,
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,3,45,3,
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,2,15,2,
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,359,22,359,
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,0,21,0,
5,female,"47,8",Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,1 436,52,1,436
6,male,"36,7",Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,122,20,122,
7,male,51,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,0,5,0,
8,female,"29,5",Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,84,19,84,
9,male,28,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,3,23,3,

In [364]:
#combine the two together again but without the initial space
sexWork_df['Hours'] = sexWork_df['Expanded_1'] + sexWork_df['Expanded_2']
#remove the unnecessary columns now that we're finished with them
sexWork_df.drop(['Expanded_1', 'Expanded_2'], axis=1, inplace = True)

sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,0,2
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,3,45
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,2,15
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,359,22
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,0,21
5,female,"47,8",Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,1436,52
6,male,"36,7",Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,122,20
7,male,51,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,0,5
8,female,"29,5",Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,84,19
9,male,28,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,3,23

In [365]:
#adds a seconds column for timedelta purposes
sexWork_df['Seconds'] = "00"
#fills in zeros for minutes
sexWork_df['Minutes'] = sexWork_df['Minutes'].astype(str).str.zfill(2)
#save the old hour format for day conversion
sexWork_df['Old_hours'] = sexWork_df['Hours']

sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,0,02,00,0
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,3,45,00,3
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,2,15,00,2
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,359,22,00,359
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,0,21,00,0
5,female,"47,8",Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,1436,52,00,1436
6,male,"36,7",Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,122,20,00,122
7,male,51,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,0,05,00,0
8,female,"29,5",Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,84,19,00,84
9,male,28,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,3,23,00,3

#### Fix Hours

In [366]:
hours = sexWork_df['Hours'].astype(int)
remaining_hours = [x if x < 24 else int(((x/24)%1)*24) for x in hours]

In [367]:
#places properly calculated hours in the Hours column
sexWork_df['Hours'] = remaining_hours
sexWork_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28819 entries, 0 to 28830
Data columns (total 18 columns):
Gender                                 28815 non-null object
Age                                    28819 non-null object
Verification                           28819 non-null object
Sexual_orientation                     28818 non-null object
Sexual_polarity                        28818 non-null object
Looking_for                            28395 non-null object
Last_login                             28819 non-null object
Member_since                           28819 non-null datetime64[ns]
Number_of_Comments_in_public_forum     28819 non-null object
Time_spent_chating_H:M                 28819 non-null object
Number_of_offline_meetings_attended    28819 non-null float64
Profile_pictures                       28819 non-null float64
Friends_ID_list                        3312 non-null object
Risk                                   28819 non-null object
Hours                                  28819 non-null int64
Minutes                                28819 non-null object
Seconds                                28819 non-null object
Old_hours                              28819 non-null object
dtypes: datetime64[ns](1), float64(2), int64(1), object(14)
memory usage: 4.2+ MB

In [368]:
#changes column type to string
sexWork_df['Hours'] = sexWork_df['Hours'].astype(str)
sexWork_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28819 entries, 0 to 28830
Data columns (total 18 columns):
Gender                                 28815 non-null object
Age                                    28819 non-null object
Verification                           28819 non-null object
Sexual_orientation                     28818 non-null object
Sexual_polarity                        28818 non-null object
Looking_for                            28395 non-null object
Last_login                             28819 non-null object
Member_since                           28819 non-null datetime64[ns]
Number_of_Comments_in_public_forum     28819 non-null object
Time_spent_chating_H:M                 28819 non-null object
Number_of_offline_meetings_attended    28819 non-null float64
Profile_pictures                       28819 non-null float64
Friends_ID_list                        3312 non-null object
Risk                                   28819 non-null object
Hours                                  28819 non-null object
Minutes                                28819 non-null object
Seconds                                28819 non-null object
Old_hours                              28819 non-null object
dtypes: datetime64[ns](1), float64(2), object(15)
memory usage: 4.2+ MB

In [369]:
#fills in zeros for hours
sexWork_df['Hours'] = sexWork_df['Hours'].astype(str).str.zfill(2)

sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,00,02,00,0
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,03,45,00,3
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,02,15,00,2
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,23,22,00,359
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,00,21,00,0
5,female,"47,8",Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,20,52,00,1436
6,male,"36,7",Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,01,20,00,122
7,male,51,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,00,05,00,0
8,female,"29,5",Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,12,19,00,84
9,male,28,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,03,23,00,3

#### Add Days

In [370]:
days = sexWork_df['Old_hours'].astype(int)
calculated_days = [0 if x < 24 else (x//24) for x in days]

In [371]:
#places properly calculated days in the new Days column
sexWork_df['Days'] = calculated_days

In [372]:
#changes column type to string
sexWork_df['Days'] = sexWork_df['Days'].astype(str)
sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours,Days
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,00,02,00,0,0
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,03,45,00,3,0
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,02,15,00,2,0
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,23,22,00,359,14
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,00,21,00,0,0
5,female,"47,8",Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,20,52,00,1436,59
6,male,"36,7",Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,01,20,00,122,5
7,male,51,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,00,05,00,0,0
8,female,"29,5",Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,12,19,00,84,3
9,male,28,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,03,23,00,3,0

In [373]:
#fills in zeros for hours
sexWork_df['Days'] = sexWork_df['Days'].astype(str).str.zfill(2)

sexWork_df.head(10)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours,Days
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,00,02,00,0,00
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,03,45,00,3,00
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,02,15,00,2,00
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,23,22,00,359,14
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,00,21,00,0,00
5,female,"47,8",Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,20,52,00,1436,59
6,male,"36,7",Non_Verified,bicurious,Submisive,Women,before_1_days,2010-10-16,1,122:20,0.0,0.0,NaN,No_risk,01,20,00,122,05
7,male,51,Non_Verified,Heterosexual,Dominant,Nobody,before_9_days,2010-10-22,91,0:5,0.0,2.0,28050,No_risk,00,05,00,0,00
8,female,"29,5",Non_Verified,bicurious,Submisive,Nobody_but_maybe,before_4_days,2013-05-23,278,84:19,3.0,4.0,"11650,15608,21357,17220,19573,8747,14635,26552...",No_risk,12,19,00,84,03
9,male,28,Non_Verified,Heterosexual,Switch,Women,before_1_days,2013-12-06,4,3:23,0.0,0.0,"40351,24148,43311",No_risk,03,23,00,3,00

In [374]:
sexWork_df['Hours'] = sexWork_df['Hours'].astype(int)
sexWork_df['Minutes'] = sexWork_df['Minutes'].astype(int)
sexWork_df['Seconds'] = sexWork_df['Seconds'].astype(int)

In [375]:
sexWork_df['Total_chat_time'] = pd.to_timedelta(sexWork_df['Hours']*3600 + sexWork_df['Minutes']*60 + sexWork_df['Seconds'], unit='s')
sexWork_df.head()

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours,Days,Total_chat_time
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,0,2,0,0,00,00:02:00
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,3,45,0,3,00,03:45:00
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,2,15,0,2,00,02:15:00
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,23,22,0,359,14,23:22:00
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,0,21,0,0,00,00:21:00

In [376]:
# sexWork_df['Total_Chat_time'] = sexWork_df['Hours'] + ":" + sexWork_df['Minutes'] + ":" + sexWork_df['Seconds']
# sexWork_df.head()

In [377]:
# sexWork_df['Total_Chat_time'] = pd.to_datetime(sexWork_df['Total_Chat_time'], format='%H:%M:%S')
# sexWork_df.head()

In [378]:
# sexWork_df['Total_chat_time'] = pd.Series([val.time() for val in sexWork_df['Total_Chat_time']])
# sexWork_df.info()

In [379]:
sexWork_df.head(6)

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Friends_ID_list,Risk,Hours,Minutes,Seconds,Old_hours,Days,Total_chat_time
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,before_10_days,2012-09-17,32,0:2,0.0,0.0,18260,No_risk,0,2,0,0,00,00:02:00
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,before_1_days,2009-01-11,710,3:45,0.0,0.0,"11778,32024,43768,23969,27318,45884,31277",No_risk,3,45,0,3,00,03:45:00
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,before_3_days,2013-01-04,25,2:15,1.0,45.0,"19805,21721,19802",No_risk,2,15,0,2,00,02:15:00
3,male,34,Non_Verified,Heterosexual,Dominant,Women,before_4_days,2013-08-04,107,359:22,0.0,1.0,"40847,38183,9507,42259,5807,28118,24848,37170,...",No_risk,23,22,0,359,14,23:22:00
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,before_5_days,2013-04-14,600,0:21,6.0,8.0,"1320,35739,34231,19097,20197,18069,12330,43342...",No_risk,0,21,0,0,00,00:21:00
5,female,"47,8",Non_Verified,Heterosexual,Dominant,Nobody_but_maybe,before_1_days,2013-04-19,159,1 436:52,9.0,0.0,"23178,22033,9547,30606,15355,9507,17023,2593,1...",No_risk,20,52,0,1436,59,20:52:00

## Representing the number of ID's as a count

In [380]:
#splitting on a comma to create lists within the dataframe while ignoring nan Values
sexWork_df['Friends_ID_list'] = sexWork_df['Friends_ID_list'].apply(lambda x: x.split(',') if not pd.isnull(x) else np.nan)
sexWork_df['Friends_ID_list'] = sexWork_df['Friends_ID_list'].str.len()
sexWork_df['Friends'] = sexWork_df['Friends_ID_list']

In [381]:
sexWork_df.drop(['Friends_ID_list', 'Total_Chat_time'], axis=1, inplace=True)
sexWork_df.drop(['Hours', 'Minutes', 'Seconds', 'Old_hours'], axis=1, inplace=True)

ValueError: labels ['Total_Chat_time'] not contained in axis

In [ ]:
sexWork_df.head(5)

In [ ]:
sexWork_df.info()

## Fixing values in 'comments' column

In [ ]:
sexWork_df[['Expanded_1','Expanded_2']] = sexWork_df['Number_of_Comments_in_public_forum'].str.split(' ', expand=True)
#fills the new 'None' values with empty space rather than NaN
sexWork_df['Expanded_2'].fillna(value='', inplace=True)

In [ ]:
#combine the two together again but without the initial space
sexWork_df['Number_of_Comments_in_public_forum'] = sexWork_df['Expanded_1'] + sexWork_df['Expanded_2']
#remove the unnecessary columns now that we're finished with them
sexWork_df.drop(['Expanded_1', 'Expanded_2'], axis=1, inplace = True)

In [ ]:
sexWork_df['Number_of_Comments_in_public_forum'] = sexWork_df['Number_of_Comments_in_public_forum'].astype(int)

In [ ]:
sexWork_df.info()

## Futher garbage value checks

To ensure no other garbage values exist in some of the columns, the "unique" call is used to inspect the contents of each column.

In [ ]:
sexWork_df['Gender'].unique()

In [ ]:
sexWork_df['Sexual_orientation'].unique()

In [ ]:
sexWork_df['Sexual_polarity'].unique()

In [ ]:
sexWork_df['Looking_for'].unique()

In [ ]:
sexWork_df['Risk'].unique()

In [ ]:
sexWork_df['Risk'].unique()

In [ ]:
sexWork_df.to_csv('../../data/raw/prepped_online_sex_work.csv', encoding='utf-8')

# Forever Alone

In [ ]:
redditThread_df = pd.read_csv('../../data/raw/foreveralone.csv')
redditThread_df.head()

In [ ]:
cols_Of_Interest_Reddit = [0, 4, 12, 13, 14, 15, 16, 18]
redditThread_df.drop(redditThread_df.columns[cols_Of_Interest_Reddit], axis=1, inplace=True)
redditThread_df.head()

In [ ]:
redditThread_df.info()

In [ ]:
redditThread_df['race'].unique() #checking for junk values or duplicates

In [ ]:
redditThread_df[redditThread_df['race'].str.contains('mixed')] #duplicates on 'mixed' cus of different cases

In [ ]:
redditThread_df.at[266, 'race'] = 'Mixed' #altering the value of mixed at it's index since. Hard coded it as it was just one duplicate

In [ ]:
redditThread_df[redditThread_df['race'].str.contains('indian')]

In [ ]:
redditThread_df.at[301, 'race'] = 'Indian'

In [ ]:
redditThread_df['race'].unique()

In [ ]:
#answer for race here doesn't seem valid.. are we keeping it? I feel it'll affect our data.
redditThread_df[redditThread_df['race'].str.contains('First two answers. Gender is androgyne, not male; sexuality is asexual, not bi.')]

In [ ]:
redditThread_df['friends'] = redditThread_df['friends'].astype(int)

In [ ]:
redditThread_df.info()

In [ ]:
redditThread_df.to_csv('../../data/raw/prepped_foreveralone.csv', encoding='utf-8')