In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [23]:
sexWork_df = pd.read_csv('../../data/raw/prepped_online_sex_work.csv')
sexWork_df.head()

,Unnamed: 0,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Points_Rank,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Risk,Days,Total_chat_time,Friends
0,0,male,"34,6",Non_Verified,Homosexual,Switch,Men,50,before_10_days,2012-09-17,32,0:2,0.0,0.0,No_risk,0,00:02:00,1.0
1,1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,518,before_1_days,2009-01-11,710,3:45,0.0,0.0,No_risk,0,03:45:00,7.0
2,2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,150,before_3_days,2013-01-04,25,2:15,1.0,45.0,No_risk,0,02:15:00,3.0
3,3,male,34,Non_Verified,Heterosexual,Dominant,Women,114,before_4_days,2013-08-04,107,359:22,0.0,1.0,No_risk,14,23:22:00,12.0
4,4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,497,before_5_days,2013-04-14,600,0:21,6.0,8.0,No_risk,0,00:21:00,35.0

In [24]:
sexWork_df.drop(sexWork_df.columns[0:1], axis=1, inplace=True)
sexWork_df.head()

,Gender,Age,Verification,Sexual_orientation,Sexual_polarity,Looking_for,Points_Rank,Last_login,Member_since,Number_of_Comments_in_public_forum,Time_spent_chating_H:M,Number_of_offline_meetings_attended,Profile_pictures,Risk,Days,Total_chat_time,Friends
0,male,"34,6",Non_Verified,Homosexual,Switch,Men,50,before_10_days,2012-09-17,32,0:2,0.0,0.0,No_risk,0,00:02:00,1.0
1,male,"32,2",Non_Verified,Heterosexual,Dominant,Women,518,before_1_days,2009-01-11,710,3:45,0.0,0.0,No_risk,0,03:45:00,7.0
2,male,"33,6",Non_Verified,Heterosexual,Dominant,Women,150,before_3_days,2013-01-04,25,2:15,1.0,45.0,No_risk,0,02:15:00,3.0
3,male,34,Non_Verified,Heterosexual,Dominant,Women,114,before_4_days,2013-08-04,107,359:22,0.0,1.0,No_risk,14,23:22:00,12.0
4,male,"39,5",Non_Verified,Heterosexual,Dominant,Women,497,before_5_days,2013-04-14,600,0:21,6.0,8.0,No_risk,0,00:21:00,35.0

In [43]:
# sexWork_df.groupby(['Sexual_polarity', 'Friends'])['Friends'].count()
sexWork_df.groupby(['Sexual_polarity','Friends']).size().reset_index().groupby('Sexual_polarity').()

                 Friends   0
Sexual_polarity
Dominant              34  34
Submisive             39  39
Switch                29  29